apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Service
metadata:
  name: ip-app
  namespace: dev
  labels:
    app: ip-app
spec:
  type: NodePort
  ports:
  - port: 8989
  selector:
    app: ip-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app
  namespace: dev
  labels:
    app: ip-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      containers:
      - name: ip-app
        image: cf/ip-app:v0.1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8989
        livenessProbe:
          httpGet:
            path: /health
            port: 8989
          initialDelaySeconds: 2
          periodSeconds: 10
